# Audio Tools — Help text & version

_name_desc() {
    local version
    version=$(cat "$(dirname "${BASH_SOURCE[0]}")/../../VERSION" 2>/dev/null || echo "unknown")
    echo "audio-tools v$version — A Bash Suite for Audio Management"
}

show_help() {
    _name_desc
    echo ""
    echo "USAGE"
    echo "    audio-tools [--help | --version]"
    echo "    audio-tools <command> [options] [<file>|<dir> ...]"
    echo ""
    echo "DESCRIPTION"
    echo "    Batch convert, clean, scan, and organize audio files from the"
    echo "    terminal. Processes WAV, OGG, FLAC, AAC, WMA, and M4A files"
    echo "    via ffmpeg."
    echo ""

    echo "CONVERSION"
    echo "    convert          WAV/OGG/FLAC/AAC/WMA/M4A -> MP3 (or --format)"
    echo "    normalize        EBU R128 loudness normalization"
    echo "    trim-silence     Remove silence from start/end of files"
    echo "    split-silence    Split audio at silence points"
    echo "    concat           Concatenate multiple audio files into one"
    echo ""
    echo "CLEANUP & ORGANIZE"
    echo "    clean            Replace spaces with _, strip special chars"
    echo "    rename           Batch rename with patterns ({n}, {orig}, {date}, {ext})"
    echo "    scan             Copy all audio from subfolders into one dir"
    echo "    remove-short     Trash files shorter than --threshold"
    echo "    remove-long      Trash files longer than --threshold"
    echo "    dedup            Remove exact duplicates by SHA256"
    echo ""
    echo "INSPECT & SEARCH"
    echo "    info             Show metadata for an audio file"
    echo "    stats            Aggregate statistics for a directory"
    echo "    list             List files with duration/size/format"
    echo "    search           Find files by keyword, delete or extract"
    echo "    find-dupes       Find (but keep) exact duplicate files"
    echo ""
    echo "SHELL"
    echo "    completion       Generate shell completion script"
    echo ""

    echo "GLOBAL OPTIONS"
    echo "    -h, --help                Print help information and exit"
    echo "    -V, --version             Print version information and exit"
    echo "    -d, --directory PATH      Target directory [default: current]"
    echo "        --files-from FILE     Read file paths from a file (one per line)"
    echo "        --progress            Show compact progress bar [default]"
    echo "        --no-progress         Show detailed per-file logs instead"
    echo "    -f, --force               Skip all confirmation prompts"
    echo "        --no-force            Always ask for confirmation [default]"
    echo "        --dry-run             Simulate without modifying files"
    echo "    -v, --verbose             Show detailed output [default]"
    echo "        --quiet               Suppress info/warn output"
    echo "    -t, --threshold SECONDS   Duration threshold for remove"
    echo "    -q, --query STRING        Filename keyword for search"
    echo "    -o, --operation OP        Operation for search: delete | extract"
    echo "        --format FMT          Output format for convert [default: mp3]"
    echo "        --bitrate RATE        Audio bitrate [default: 320k]"
    echo "        --max-depth N         Max recursion depth [default: unlimited]"
    echo "        --pattern PAT         Rename pattern: {n} {orig} {date} {ext}"
    echo ""
    echo "You may pass one or more files or directories as positional arguments"
    echo "after the command. They are auto-detected and processed together with"
    echo "--directory (if given). When nothing is specified, defaults to pwd."
    echo ""
    echo "ENVIRONMENT"
    echo "    AUDIO_TOOLS_FORMAT           Default --format [default: mp3]"
    echo "    AUDIO_TOOLS_BITRATE          Default --bitrate [default: 320k]"
    echo "    AUDIO_TOOLS_CONVERTED_DIR    Output dir for convert [default: converted_mp3]"
    echo "    AUDIO_TOOLS_SCAN_DIR         Output dir for scan [default: ALL_AUDIOS]"
    echo "    AUDIO_TOOLS_FORCE            Skip prompts when set to yes"
    echo "    AUDIO_TOOLS_QUIET            Suppress output when set to yes"
    echo "    AUDIO_TOOLS_CONFIG           Config file path"
    echo "    NO_COLOR                     Disable ANSI color output"
    echo ""

    echo "EXAMPLES"
    echo "    audio-tools convert --format flac --bitrate 192k"
    echo "    audio-tools convert song.wav"
    echo "    audio-tools convert song1.wav song2.wav ./samples"
    echo "    audio-tools convert --files-from list.txt --directory ./backup"
    echo "    audio-tools info track.flac"
    echo "    audio-tools stats ./library"
    echo "    audio-tools normalize song.wav"
    echo "    audio-tools rename song.wav --pattern '{n}_{orig}' --dry-run"
    echo "    audio-tools dedup song1.wav song2.wav --dry-run"
    echo "    audio-tools remove-short --threshold 2 --force"
    echo ""

    echo "EXIT STATUS"
    echo "    0    Success"
    echo "    64   Usage error"
    echo "    69   ffmpeg/ffprobe not found"
    echo "    74   I/O error"
    echo ""

    echo "SEE ALSO"
    echo "    ffmpeg(1)    https://ffmpeg.org/"
    echo "    ffprobe(1)   https://ffmpeg.org/"
    echo "    Project      https://github.com/ekosistema/audio-tools"
}

show_version() {
    local version
    version=$(cat "$(dirname "${BASH_SOURCE[0]}")/../../VERSION" 2>/dev/null || echo "unknown")
    echo "audio-tools v$version"
}
